apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: mimarisozluk-net-tls
spec:
  secretName: mimarisozluk-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mimarisozluk.net
  dnsNames:
    - mimarisozluk.com
    - www.mimarisozluk.net